name: ðŸ› Bug Report
description: File an issue about a bug in TextArena.
title: "[BUG] "
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please provide detailed information to help us reproduce and fix the issue in TextArena.
  - type: checkboxes
    id: steps
    attributes:
      label: Required prerequisites
      description: Make sure you've completed the following steps before submitting your issue -- thank you!
      options:
        - label: I have searched the [Issue Tracker](https://github.com/LeonGuertler/TextArena/issues) that this hasn't already been reported. (comment there if it has.)
          required: true
  - type: dropdown
    id: component-type
    attributes:
      label: Component type
      description: What type of component does this bug affect?
      options:
        - Game-specific (affects a particular game)
        - Core platform (affects the TextArena framework)
        - UI/UX (affects user interface)
        - API/Integration
        - Documentation
        - Other (please specify in description)
    validations:
      required: true

  - type: input
    id: game-name
    attributes:
      label: Game name (if applicable)
      description: If this is a game-specific bug, please enter the exact name of the affected game.
      placeholder: e.g., Chess, TicTacToe, SpellingBee, etc.
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Problem description
      description: >-
        Provide a clear description of the bug. What happened? What did you expect to happen?
        Include information like which game was affected, what specific action triggered the bug, etc.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: >-
        List the exact steps needed to reproduce the bug. For game-specific bugs,
        include the game state, player actions, and any input provided.
      value: |
        1. Start the game [name of game]
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Code example / Observation
      description: >-
        If applicable, provide a code snippet that demonstrates the issue or the relevant
        game observation that shows the bug in action.
      value: |
        ```python
        # Code example or observation text here
        ```
    validations:
      required: true
  - type: textarea
    id: traceback
    attributes:
      label: Error message / Traceback
      description: If applicable, paste the full error output or traceback here.
      render: pytb
  - type: textarea
    id: system-info
    attributes:
      label: System information
      description: |
        Describe your environment:
        - Python version
        - Browser/client (if relevant)
        - TextArena version or commit hash
        - Any other relevant dependencies
      value: |
        ```
        Python version:
        TextArena version/commit:
        ```
  - type: textarea
    id: fix-suggestion
    attributes:
      label: Suggested fix
      description: If you have ideas on how to fix this issue, please share them here.
